name: Build and push container image
on:
  push: 
    branches: ['main']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  ci:
    name: Run CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
        with:
          version: "0.5.2"
      - run: uv python install 3.12
      - name: ruff check
        run: uv run ruff check
      - name: ruff format
        run: uv run ruff format --check --diff

  build-and-push:
    needs: ci
    permissions: 
      contents: read
      packages: write
      attestations: write
      id-token: write

    name: Build and push
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: echo "SHA_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
        id: short-hash
      - uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
                ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
                ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.short-hash.outputs.SHA_SHORT }}
